# Generated by Django 2.2.2 on 2021-08-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=10, verbose_name='飞机编号')),
                ('flight_company', models.CharField(max_length=30, verbose_name='飞机从属航空公司')),
                ('departure', models.CharField(max_length=10, verbose_name='始发地')),
                ('destination', models.CharField(max_length=10, verbose_name='目的地')),
                ('begin_time', models.DateTimeField(verbose_name='起飞时间')),
                ('end_time', models.DateTimeField(verbose_name='落地时间')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TakeFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_type', models.CharField(choices=[('passenger', '旅客'), ('flight', '机组人员')], default='passenger', max_length=10, verbose_name='乘客类型')),
                ('passenger_id', models.IntegerField(verbose_name='乘客编号')),
                ('passenger_name', models.CharField(max_length=10, verbose_name='乘客姓名')),
                ('is_take', models.CharField(choices=[('Y', '是'), ('N', '否')], default='N', max_length=1, verbose_name='乘客是否乘机')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flight.Flight', verbose_name='航班编号')),
            ],
        ),
    ]
