# Generated by Django 2.2.2 on 2021-08-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeflight',
            name='flight_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flight.Flight', verbose_name='航班编号'),
        ),
    ]
