# Generated by Django 2.2.2 on 2021-08-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_takeflight_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='地区名称')),
                ('infect_level', models.CharField(choices=[('1', '低风险'), ('2', '中风险'), ('3', '高风险')], default='1', max_length=1, verbose_name='感染风险等级')),
            ],
        ),
    ]
