# Generated by Django 2.2 on 2021-08-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('decription', models.CharField(max_length=255)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'deptinfo',
                'ordering': ['-id'],
            },
        ),
    ]
