# Generated by Django 3.2.4 on 2021-08-09 10:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('decription', models.CharField(max_length=255)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'deptinfo',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('birthday', models.DateTimeField(default=datetime.datetime.now, verbose_name='生日')),
                ('salary', models.FloatField(verbose_name='工资')),
                ('isDelete', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='demo.deptinfo')),
            ],
        ),
    ]
