# Generated by Django 2.2.2 on 2021-08-12 15:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='出勤时间')),
                ('monitor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.Monitor', verbose_name='监测点编号')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='TaskFinish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finish', models.CharField(choices=[('Y', '是'), ('N', '否')], default='N', max_length=1, verbose_name='出勤人员是否到勤')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='出勤人员编号')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.Task', verbose_name='出勤任务编号')),
            ],
        ),
    ]
