# Generated by Django 2.2.2 on 2021-08-16 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='monitor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='monitor.Monitor', verbose_name='监测点编号'),
        ),
        migrations.AlterField(
            model_name='taskfinish',
            name='staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='出勤人员编号'),
        ),
        migrations.AlterField(
            model_name='taskfinish',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task.Task', verbose_name='出勤任务编号'),
        ),
    ]
