# Generated by Django 2.2.2 on 2021-08-12 15:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfectRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infect_level', models.CharField(choices=[('1', '低风险'), ('2', '中风险'), ('3', '高风险')], default='1', max_length=1, verbose_name='感染风险等级')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
                ('monitor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.Monitor', verbose_name='监测点编号')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='InfectAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_level', models.CharField(choices=[('1', '低风险'), ('2', '中风险'), ('3', '高风险')], max_length=1, verbose_name='感染警示等级')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='警示时间')),
                ('risk_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alarm.InfectRisk', verbose_name='感染风险预警编号')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='机场管理人员编号')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
