# Generated by Django 2.2.2 on 2021-08-16 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectalarm',
            name='risk_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alarm.InfectRisk', verbose_name='感染风险预警编号'),
        ),
        migrations.AlterField(
            model_name='infectalarm',
            name='staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='机场管理人员编号'),
        ),
        migrations.AlterField(
            model_name='infectrisk',
            name='monitor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='monitor.Monitor', verbose_name='监测点编号'),
        ),
    ]
