# Generated by Django 2.2.2 on 2021-08-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0002_auto_20210816_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infectalarm',
            name='alarm_level',
            field=models.CharField(choices=[('2', '中风险'), ('3', '高风险')], max_length=1, verbose_name='感染警示等级'),
        ),
    ]
