# Generated by Django 2.2.2 on 2021-08-05 15:56

from django.db import migrations, models
import utils.FileUtils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210805_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='avatar/default.jpg', storage=utils.FileUtils.ImageStorage(), upload_to='avatar/%Y/%m', verbose_name='用户头像'),
        ),
    ]
