# Generated by Django 2.2 on 2021-08-10 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('log_type', models.CharField(max_length=255, verbose_name='操作模块')),
                ('log_ip', models.CharField(max_length=20, verbose_name='操作ip地址')),
                ('log_content', models.CharField(max_length=255, verbose_name='操作内容')),
            ],
        ),
    ]
