# Generated by Django 2.2.2 on 2021-08-08 22:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('log_type', models.CharField(max_length=255, verbose_name='操作模块')),
                ('log_ip', models.CharField(max_length=20, verbose_name='操作ip地址')),
                ('log_content', models.CharField(max_length=255, verbose_name='操作内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
        ),
    ]
