# Generated by Django 2.2.2 on 2021-08-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='user',
            new_name='log_user',
        ),
    ]
