# Generated by Django 2.2.2 on 2021-08-16 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20210809_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='log_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作者'),
        ),
    ]
