# Generated by Django 2.2.2 on 2021-08-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210809_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='wechat',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=0, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='card_id',
            field=models.CharField(max_length=20, null=True, verbose_name='身份证号码'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='flight_type',
            field=models.CharField(blank=True, choices=[('pilot', '飞行员'), ('service', '空勤人员')], max_length=8, null=True, verbose_name='职务'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='infect_level',
            field=models.CharField(choices=[('1', '低风险'), ('2', '中风险'), ('3', '高风险')], default='1', max_length=1, verbose_name='感染风险等级'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='person_type',
            field=models.CharField(choices=[('passenger', '旅客'), ('airport', '机场工作人员'), ('flight', '机组人员')], default='passenger', max_length=10, verbose_name='人员类型'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='task_type',
            field=models.CharField(blank=True, choices=[('security', '安保'), ('cleaning', '保洁'), ('check-in', '值机服务')], max_length=10, null=True, verbose_name='工种'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(max_length=20, null=True, verbose_name='手机号码'),
        ),
    ]
