# Generated by Django 2.2.2 on 2021-08-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userinfo_today_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='today_login',
        ),
    ]
